import { useEffect } from "react";

const Bigmed2001Bigonnet = () => {
  const BASE_URL = import.meta.env.BASE_URL;
  useEffect(() => {
    document.body.style.backgroundColor = "beige";
    document.body.style.backgroundImage = `url(${BASE_URL}barks/paper2.gif)`;
    document.body.style.color = "#000000";
    return () => {
      document.body.style.backgroundColor = "";
      document.body.style.backgroundImage = "";
      document.body.style.color = "";
    };
  }, []);

  const html = `

<CENTER>
<IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=75% HEIGHT=5><BR>
<BLOCKQUOTE><BLOCKQUOTE><STRONG> <FONT  SIZE=5 COLOR=#000055>  B<FONT SIZE=3>IG</FONT> O<FONT SIZE=3>NLINE </FONT> <BR><FONT  SIZE=3>Revealing introductory texts and resources to bring you <BR>up to speed on Big Body symptoms &amp; strategies.</STRONG></BLOCKQUOTE></BLOCKQUOTE>
<IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=75% HEIGHT=5><P>

<TABLE>
<TR><TD><STRONG><UL>
<LI><A HREF="#global">Globalization (New Buzzword for Big Body Dominion)</A>
<LI><A HREF="#usa">Big Body Rule - US Political/Social Effects</A><BR>
<LI><A HREF="#soma">Big Body Anthroculture - Psychosomatic Effects</A> 
</UL></STRONG></TD></TR>
</TABLE>

<IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=75% HEIGHT=5>


</CENTER>
<BLOCKQUOTE>      <P>

<A NAME="global"></A>
<STRONG><U>R<FONT SIZE=-1>ECLAIMING THE PLANET</FONT></U><BR><font size="4">Globalization &amp; Big Body Dominion</font></STRONG><BR></STRONG>
<FONT  COLOR=#800000 size="3">Recently the most intense attention to Big Bodies has been generated by their historic victories in subordinating all sensual, spiritual and cultural aspects of our planetary experience to their primitive economic  appetites. Since their continued evolution and dominance as social organisms demands ever increasing trade, production/consumption and corporate growth, they have made these the cardinal values of the New World Order. To enforce these values, they have created new legal weapons like NAFTA, GATT and MAI and a whole class of auxilliary bodies like the IMF and the WTO to clear human obstacles to their manifest destiny - obstacles like our hard-won laws against food/air/water pollution, environmental rape, worker exploitation, the destruction of  cultural and biological diversity, etc. In spite of its predictably low profile in the corporate media, every sentient being should know about this lethal offensive. Try these links for starters.</FONT></BLOCKQUOTE>
<UL>
<LI>             <DL> <DT><A HREF="http://www.context.org/ICLIB/IC36/Korten.htm" target="_blank"><STRONG>Global Integration; Global Rule</STRONG></A><dd>Clear statement of the perils we face when the global appetites of Big Bodies converge by David "When Corporations Rule the World" Korten</DL><P>

<LI>        <DL><DT><A HREF="http://adbusters.org/campaigns/question/" target="_blank">
<STRONG>The BIG Question</STRONG></A> - Is Economic Growth Killing the Planet            By Kalle Lasn <dd>Primal force behind the Media Foundation, Adbusters and Culture Jamming subversion. Lasn is a true renaissance man of the Big Body resistance. See also Adbuster's inspiring  <A HREF="http://www.adbusters.org/campaigns/" target="_blank">Anti-Big Campaign List</A> which deftly counters the cynical fantasies of Big Body economics.
<BLOCKQUOTE>"The difference between science and economics," says F.E. Banks in
                           Truth and Economics, "is that science aims at an understanding of the
                           behavior of nature, while economics is involved with an understanding
                           of models - and many of these models have no relation to any state of
                           nature that has ever existed on this planet, or any that is likely to exist
                           between now and doomsday. The word that comes to mind when
                           confronted by these fantasies is fraud." </BLOCKQUOTE>
</DL><P>
<LI>        <DL><DT><A HREF="http://www.ratical.com/LifeWeb/Articles/globalize.html" target="_blank">
<STRONG>The Biology of Globalization</STRONG></A>  by Elisabet Sahtouris<dd>An eloquent evolutionary biologist's wise and powerful recounting of current planetary pathology. <BLOCKQUOTE>"To see why the current course of globalization cannot continue and must be changed to a healthier
     one, we need to look at the inherent contradictions between what we have euphemistically called
     "free market capitalism" (in fact an incipient global totalitarian capitalism) and what we should have: a
     democratic and ecologically sound economic system. I want to discuss this fundamental contradiction
     from a biological perspective, but let's look first at the pattern of growing opposition to corporate
     globalization without representation..."</BLOCKQUOTE></DL>
<P>

<LI>     <DL> <DT><A HREF="http://www.preamble.org/MAI/maihome.html" target="_blank"><STRONG>Globalization and the MAI</STRONG></A><DD>If you don't already know about the Big Body-driven Multilateral Agreement on Investment and the increased havoc it will inflict on Third World economies and our most enlightened domestic laws, start here. A strong, authoritative collection of analysis/documents on the Great Takeover.</DL><P>

<UL>
 "What does the MAI mean?
<LI>                  Governments will be required to offer multinational corporations the same benefits
                  as those offered to any local investor, including non-profit groups and government organisations.
<LI>                   Multinational corporations will be able to sue any government that does anything
                  that has the effect of 'expropriating' their investment. For example, enforcing environmental
                  regulations, recognizing native title, supporting trade union rights, etc.
<LI>                 It will be illegal for governments to boycott a company because of its activities
               in another country, even if that company is savaging the environment, exploiting workers and/or supporting bloody dictatorships."
</UL></DL><br>
<LI>        <DT><A HREF="http://www.flora.org/flora.mai-not/3264" target="_blank">
<STRONG>MAI - World Wide</STRONG></A><dd>Long, annotated list of important websites &amp; online resources.

</UL>
<P>
<CENTER><IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=85% HEIGHT=5></CENTER>
<P>
<A NAME="usa"></A>
<STRONG><U>R<FONT SIZE=-1>ECLAIMING THE COUNTRY</FONT></U><BR>The Big Body Plague - US Political/Social Effects <BR>( A VERY Short List of Typical Symptoms) </STRONG><P>
<TABLE CELLSPACING=7>
<TR><TD ALIGN=MIDDLE width=70>
</TD>
<TD>
<UL>
<LI><A HREF="#corrupt"><STRONG>Epidemic Corruption of Leaders &amp; Elections</STRONG></A>
<LI><A HREF="#theft"><STRONG>Parasitic Tax Theft</STRONG></A>
<LI>                             <A HREF="#power"><STRONG>Malignant Concentrations of Power</STRONG></A>
<LI>                         <A HREF="#arms"><STRONG>Pathological Arms Budgets</STRONG></A>
<LI>            <A HREF="#science"><STRONG>Mercenary Science</STRONG></A>
<LI>            <A HREF="#educorp"><STRONG>Anesthetized Education</STRONG></A>
<LI>                    <A HREF="#food"><STRONG>Toxic Food &amp; Water</STRONG></A>
<LI>                        <A HREF="#environment"><STRONG>Environmental Devastation</STRONG></A>
<LI>            <A HREF="#media"><STRONG>Deaf &amp; Dumb Media</STRONG></A>
<LI>                         <A HREF="#chronic"><STRONG>Chronic Personal Dis-ease</STRONG></A>

</UL>
</TD></TR>
</TABLE>
<CENTER><IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=85% HEIGHT=5></CENTER><P>


<A NAME="corrupt"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Corruption of Leaders &amp; Elections</U></STRONG></FONT>
<UL>
<LI>       <DL> <DT><A HREF="http://www.infact.org/hos.html#ANCHOR4" target="_blank"><STRONG>Big Business Out of Congress!</STRONG></A> INFACT's  Hall of Shame Campaign</DL>
<LI>       <DL> <DT><A HREF="http://www.publicintegrity.org/buying_questions.html" target="_blank"><STRONG>The Big Body Buyout of the President</STRONG></A> Public Integrity explains the who and how</DL>
<LI>       <DL> <DT><A HREF="http://www.publicintegrity.org/Congress_main.html" target="_blank"><STRONG>The Big Body Congressional Buyout</STRONG></A> Ditto but cheaper by the dozen</DL>
<LI>     <A HREF="http://www.mojones.com/coinop_congress/coinop_congress.html" target="_blank">
<STRONG>
The Coin-Operated Congress</STRONG></A> - Mother Jones on Pay-per-Play Politics<BR>
<LI>       <DL> <DT><A HREF="http://www.publicampaign.org/goldenleash.html" target="_blank"><STRONG>The Golden Leash Awards</STRONG></A><DD>"Focused on the outrageous favors, access or trade-offs purchased from our political leaders with Big Body campaign contributions" For example:</DL>


</UL>
<A NAME="theft"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Legalized Theft</U></STRONG></FONT>
<UL>
<LI>            <DL>  <DT><A HREF="http://www.nader.org/releases/63099.html" target="_blank"><STRONG>Nader's Congressional Testimony on Corporate Welfare</STRONG></A> June 30, 1999<dd>In the Congress' first formal hearing ever on this chronic scandal (now costing US citizens over \$100 billion/year), Brother Ralph delivers the definitive explanation, analysis  and indictment.<P>
<STRONG>Edited Excerpts</STRONG><BR>
 "If a program involves the government giving more to private companies than it gets back --
   that is, where it is engaging in a transaction that cannot be justified as a fair market value exchange -- then it
   should be considered corporate welfare...<P>

"Government giveaways; government-funded research and
   development; bailouts; tax expenditures;  loans and loan guarantees; state
   and local corporate welfare; export and overseas marketing assistance; loans and loan guarantees; and grants and direct subsidies
 totaled more than \$76 billion in fiscal year 1999, according to conservative estimates by the Office of
   Management and Budget. For the five-year period 2000-2004, the government will spend more than \$394
   billion on corporate tax subsidies...<P>

"In one of the single biggest giveaways in U.S. corporate welfare history, the Federal Communications
   Commission (FCC) on April 7, 1997 donated broadcast licenses for digital television to existing broadcasters...

   Under the terms of the giveaway, the broadcasters will pay nothing for the exclusive right to use the public
   airwaves, even though the FCC itself estimated the value of the digital licenses to be worth \$11 billion to \$70
   billion...The giveaway was mandated, in part, by the 1996 Telecommunications Act, which prohibited, under demands
   by the broadcaster lobby, the FCC from auctioning off the airwaves. The Telecommunications Act also
   required the FCC, if it decided to allocate the licenses, to give them only to incumbent broadcasters."


</DL>
</UL>


<A NAME="power"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Malignant Power</U></STRONG></FONT>
<UL>
<LI>       <DL> <DT><A HREF="http://www.thecorporatelibrary.com/power/Welcome.html" target="_blank">
<STRONG>Power and Accountability</STRONG></A> by Robert Monks & Nell Minow<dd>
"Corporations determine far more than any other institution the air we breath, the quality of the water we drink, even where we live.  Yet they are not accountable to anyone." Full text online - a fine public service.</DL>

<LI>       <DT><A HREF="http://www.verdant.net/corp.htm" target="_blank"><STRONG>
Corporate Power, Influence, Money, <BR>and Interlocking Boards of Directors</STRONG></A>

</UL>
<A NAME="arms"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Unstoppable Arms Production</U></STRONG></FONT>
<UL>

<LI>        <DL><A HREF="http://www.cdi.org/adm/1224/transcript.html" target="_blank"><STRONG>
Why is Military Spending Going Up?</STRONG></A><DD>

"At \$280 billion, U.S. military spending dwarfs that of any other
                                   nation. Yet the White House, the Pentagon, and the Congress
                                   are on the verge of increasing military spending by more than
                              \$100 billion.  Although the Cold War ended almost a decade ago, the
                              United States is about to return to Cold War budgets.  At a time when
                              military spending worldwide continues to drop and with no significant
                              threat to U.S. national security, why is such a major funding increase
                              necessary?"</DL><BR>




<LI>        <DT><A HREF="http://www.mnsinc.com/pogo/mici/miciprod.html" target="_blank"><STRONG>
  Military Industrial Complex Initiative</STRONG></A> by the Project on Government Oversight<BR>

<LI>        <DL><DT><A HREF="http://www.foreignpolicy-infocus.org/papers/micr/companies.html" target="_blank"><STRONG>The Military-Industrial Complex Revisited</STRONG></A><dd>Ever feel that our peculiar Kosovo and Iraq strategies were chiefly dictated by our weapons industries' lust for subsidized product testing?</DL><BR>

<LI>        <DL><DT><A HREF="http://hs1.hst.msu.edu/~hst306/documents/indust.html" target="_blank"><STRONG>
Dwight D. Eisenhower's Military-Industrial Complex Speech</STRONG></A><DD>1961 - The Old Man's finest hour - and nobody was listening. One of the Top 10 reasons why we blew the Sixties...</DL>

</UL>

<A NAME="science"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Suborned Science</U></STRONG></FONT>
<UL>
  <LI>     <DT><a href="http://www.essential.org/monitor/mm1998/mm9801.09.html" target="_blank"><STRONG>
Corporate Junk Science</STRONG></A> - Corporate Influence at  International Science Organizations<BR>

  <LI>      <DL><DT><a href="http://www.igc.org/cna/news/abc82698.html" target="_blank"><STRONG>Don�t Tell, Don�t Ask</STRONG></A><DD>
"Corporate suppression of research results can threaten  public health, and  ruin the careers of  scientists who insist on publishing negative data."</DL><BR>

  <LI>      <DT><a href="http://www.thenation.com/issue/990322/0322shenk.shtml" target="_blank"><STRONG>
Money + Science = Ethics Problems</STRONG></A> -     Pharmaceutical Big Bodies Suppression of Cheaper, Safer Drugs<BR>

  <LI>      <DT><a href="http://www.rtis.com/reg/bcs/pol/touchstone/February96/mark.htm" target="_blank"><STRONG>
Corporate Propaganda Masquerading as Research</STRONG></A><BR>

  <LI>      <DL><DT><a href="http://www.ase.org.uk/publish/jnews/ssr/bedersep98.html" target="_blank"><STRONG>
The Corporate Infiltration of Science Education</STRONG></A> School Science Review    <DD>

"Procter & Gamble has
produced a variety of educational packages including Decision Earth, which was distributed to almost 75 000 schools
in the US... In defence of P&G's clear-cut forestry practices, the package stated: 

     <BLOCKQUOTE><EM>Clear cutting removes all trees within a stand of a few species to create new habitat for wildlife.
     Procter & Gamble uses this economically and environmentally sound method because it most
     closely mimics nature's own processes... Clear cutting also opens the forest floor to sunshine, thus
     stimulating growth and providing food for animals</EM>.</BLOCKQUOTE>
As one writer points out: 'Imagine,  your target market not only reads your ads, they get tested on them!'. One kit put out by Teacher Support Software, which is used in many kindergartens in Texas, includes test questions such as 'Taco Bell has [blank] and burritos'." </DL></UL>

<A NAME="educorp"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Anesthetized Education</U></STRONG></FONT>
<UL>
  <LI>      <DL><DT><a href="http://www.flagpole.com/Issues/01.06.99/strangebed.html" target="_blank"><STRONG> Strange Bedfellows: The new corporate influence on higher education</STRONG></A><DD>
"The only place we're free from corporate influence is in our bathrooms," says Lawrence Soley, a journalism professor at Marquette University. "Corporations have become so large and so intrusive that what's happening at universities is just symptomatic of a larger phenomenon."
</DL>

  <LI>      <DT><a href="http://www.salonmagazine.com/it/feature/1999/01/06feature.html" target="_blank">
<STRONG>Bartering Brains for Bread</STRONG></A> "Turning the Campus into a Company Town" 


  <LI>      <DL><DT><a href="http://www.canadiandimension.mb.ca/archive/ed30-5.htm" target="_blank">
<STRONG>Corporate Commodification of Education</STRONG></A>  - Canadian Dimension Editorial<DD>
"The heightened corporate effort to commodify education shows just how appealing a market students are. Just like professional sports teams, schools are able to deliver to their corporate clients a specifically targeted audience.  Add to this the fact that students spend nearly half their time in school, insulated from conventional advertising, and you have a market of potential consumers so desirable to corporate interests that multinationals are lining up to offer free pizzas, sports equipment, even televisions -- providing the TVs are used to show commercials for the companies which provided them."
</DL>

  <LI>      <DT><a href="http://www.thehoya.com/viewpoint/012299/view4.htm" target="_blank"><STRONG>
Where�s the Outrage? Student Apathy is the Result of Corporate Influence</STRONG></A>

  <LI>      <DT><a href="http://www.lbbs.org/ZMag/articles/oct96cardella.htm" target="_blank"><STRONG>
School-to-Work, A Corporate Raid on Public  Education</STRONG></A>


<LI>       <DT> <a href="http://www.osstf.on.ca/www/services/library/whatsnew/bibliog/corpinvol.html" target="_blank">
<STRONG>Corporate Involvement in Education: Bibliography</STRONG></A>

</UL>
<A NAME="food"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Endangered Food Supply</U></STRONG></FONT>
<UL>


  <LI>       <DL> <DT><a href="http://www.safe-food.org/welcome.html" target="_blank"><STRONG>Mothers for Natural Law</STRONG></A><DD> "You ARE eating  genetically engineered food.  Is it good for you?  Do you have a choice?"<BR></DL>

  <LI>      <DT><a href="http://www.natural-law.ca/genetic/ScientistsonDangers.html" target="_blank"><STRONG>Genetically Engineered Foods</STRONG></A> - Eminent Scientists Comment on their Dangers<BR>
<LI>      <DT><A HREF="http://www.enviroweb.org/issues/biotech/bgh/" target="_blank"><STRONG>Bovine Growth Hormone</STRONG></A> Big Body Milk -- Curdling Research Reports<BR>
  <LI>    <DT><a href="http://www.purefood.org/corplink.html" target="_blank"><STRONG>Corporate Food News: Abuses of Power - 1999</STRONG></A><BR>
  <LI>     <DT><a href="http://www.zero.com.au/agen/html/body_corporate_control_01.html" target="_blank"><STRONG>Corporate Food Control</STRONG></A><BR>

  <LI>     <DL><DT><a href="http://www.pbs.org/wgbh/pages/frontline/shows/nature/interviews/forsythe.html" target="_blank"><STRONG>PBS FRONTLINE's "Fooling With Nature"</STRONG></A><DD> Astonishing confessional interview with Dawn Forsythe, former manager of government affairs for Sandoz Agro Inc. [now Novartis AG] who headed the pesticide industry's first committee on endocrine disruptors until she resigned in shame and disgust. If you only read one in this section, read THIS!</DL>
</UL>
<A NAME="environment"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Assaults on the Environment</U></STRONG></FONT><BR>
<UL>
<BLOCKQUOTE><FONT  COLOR=#800000>Big Body predations in this realm are already countless and infamous - from nuclear power and agrobiz soil annihilation to clear-cut forests and global warming. I include only a few sites here that I just belatedly discovered, but which certainly could use some Big Medicine of their own.</FONT></BLOCKQUOTE>






<LI>       <DL> <DT><A HREF="http://www.igc.org/peg/toxic_empire/" target="_blank"><STRONG>Toxic Empire: The WMX Corporation</STRONG></A><DD> "One of the 100 largest corporations in the world with revenues of nearly \$10 billion a year... The San Diego District Attorney describes WMX's history as "a combination of environmental abuses, anti-trust violations and public corruption cases."</DL>

<LI>       <DL> <DT><A HREF="http://www.sprawl-busters.com/" target="_blank"><STRONG>Sprawl Busters</STRONG></A> <DD>"Your town is threatened by a Corporate Mega-Mall? Who ya gonna call?" A creative coalition of communities trying to protect their downtowns, small businesses and neighborhood feeling from Big Body rape and pillage.</DL><BR>

  <LI>      <DL><DT><a href="http://www.uwsp.edu/geo/courses/geog100/SolidWaste-Consume.htm" target="_blank"><STRONG>
Consumerism: Profiting from Waste</STRONG></A> 


  <LI>      <DL><DT><a href="http://www.ozone.org/" target="_blank"><STRONG>
OzoneACTION  Corporate Influence</STRONG></A> Read &amp; LEARN:

<UL>
<LI>What the Global Climate Coalition (an industry front group) is doing to undermine the scientific consensus on climate change.
<LI>How the polluters' lobby is using phony front groups to attack the Kyoto global warming treaty.
<LI>The Truth behind the U.S. oil and auto companies' \$13 million dollar fossil fuel ad campaign.
<LI>More dirty tricks from the oil companies' "Committee to Preserve American Security and Sovereignty" <P>

</UL></DL>
<LI>    <A HREF="http://www.ewg.org/dirtymoney/"  target="_blank"><STRONG>Big Body Money &amp; Environmental Politics</STRONG></A> - by the Environmental Working Group
</UL>
<A NAME="media"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Media Censorship</U></STRONG></FONT>
<UL>
<LI>       <DL> <DT> <a href="http://www.sonoma.edu/pubs/release/2001/091.html" target="_blank"><STRONG>Project Censored's Top 25 Stories of 2000</STRONG></A><DD> You will kindly note that over 80% of these stories involve Big Body crimes, malfeasance and/or corruption.</DL><BR>

<LI>       <DL> <DT> <a href="http://www.simedia.org/new/wamedbiz.html" target="_blank"><STRONG>
Interview with Professor Ben Bagdikian</STRONG></A><DD>
      - How the American media do business
<BLOCKQUOTE><STRONG>BB:</STRONG> I took each of these major media industries and measured which companies together
     had half or more of the business. In the case of newspapers, for example, a handful of
     companies have 51 per cent of the national average of daily circulation. In the case of
     television, three corporations have about 75 per cent of the business.<P>

     <STRONG>SI:</STRONG> Don�t we have anti-monopoly laws that are supposed to prevent this kind of
     thing from happening?<P>

     <STRONG>BB:</STRONG> They have been put to sleep..., interpreted into coma.<P>

     <STRONG>SI:</STRONG> By whom?<P>

     <STRONG>BB:</STRONG> By the federal government responding to corporate influence. But it is not a single,
     direct influence. It is a large, overwhelming, seamless web of the involvement of corporate
     interests -- banking, financial, industrial -- in the support of members of Congress and
     the presidency; in their presence in Washington where they have become almost partners
     in the making of regulations and laws; and where necessary, in flooding the media with
     information that supports their points of view.</BLOCKQUOTE></DL>

<LI>        <DL><DT><A HREF="http://www.preamble.org/columns/weisbrot/naiman/media.htm" target="_blank"><STRONG>News Media Need Public Oversight</STRONG></A> - 

- Naiman columns from the Sunday Journal, (Washington, D.C.)<DD>
"Given the existing concentration of economic resources, the mere absence of government censorship is not
enough to ensure a truly independent media. NBC is owned by General Electric, ABC by Disney, and CBS by
Westinghouse. These corporations have particular interests. In the short term they are interested in maximizing
profits. But they also have strategic interests. It�s not surprising that you don�t see a lot of press coverage of the
negative impact of mergers on consumer prices, or mass layoffs, or the increasing concentration of corporate political
power. And when these media corporations maximize profits, that means maximizing advertising dollars which could
be hurt if their reporting offends other big corporations which are largely the source of those dollars."</DL><P>


<LI>      <DT><A HREF="http://infoweb.magi.com/~ccpa/wintert.html" target="_blank"><STRONG>How the Media Smother the Facts</STRONG></A> - by James Winter, Ph.D.<dd>
       "Canada's corporate media promote the corporate agenda..."




 

</UL>
<A NAME="chronic"></A>
<FONT  SIZE=-1 FACE="Arial,Helvetica"><STRONG><U>Chronic Personal Discontent</U></STRONG> </FONT>
<UL>
<LI>        <DL><DT><A HREF="http://www.pbs.org/kcts/affluenza/" target="_blank"><STRONG>Affluenza</STRONG></A><dd>
"Af-flu-en-za n. 
<OL>
<LI> The bloated, sluggish and unfulfilled   feeling that results from efforts to keep up with the Joneses.
<LI> An epidemic of stress, overwork, waste and indebtedness caused by dogged pursuit of the 'American     Dream'. 
<LI> An unsustainable addiction to economic growth.
<LI> A television program that could change your life."
</OL>
Just their home page info on diagnosing and treating this plague is worth a crate of anti-corporate apples.
</DL>

<LI>       <DL> <DT> <a href="http://www.verdant.net/" target="_blank">
<STRONG>Overcoming Consumerism</STRONG></A><DD>A sprawling seditious self-help site with great ideas on everything from regaining your sanity to kicking Big Body ass.</DL>
<br>
<LI>       <DL> <DT> <a href="http://www.indiana.edu/~wanthro/museum.htm" target="_blank">
<STRONG>Museum of Weird Consumer Culture</STRONG></A><DD>Check out the great deal on dog diapers.</DL>
<br>
<LI>       <DL> <DT> <a href="http://www.theonion.com/onion3524/stupid_shit.html" target="_blank">
<STRONG>"Should the U.S. Impose Limits on Incredibly Stupid Shit?"</STRONG></A><DD>American perspective from The Onion.</DL>
</UL>


<P>
<CENTER><IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=100% HEIGHT=5></CENTER>
<P>
<A NAME="soma"></A>
<STRONG><U>R<FONT SIZE=-1>ECLAIMING THE BODY EROTIC </FONT></U><BR>Big Body Anthroculture - Psychosomatic Effects</STRONG><P>
<BLOCKQUOTE><FONT  COLOR=#800000>Stripped to its bare essentials, anthroculture is simply corporate animal husbandry, a technology for arresting human - particularly male - development so people will cheerfully accept a life-time of amoral subordinate service within a corporate membrane. The ancient Chinese practised a primitive form of anthroculture when they routinely castrated all their bureaucrats to ensure loyalty and reflexive obedience. We've advanced a bit since then and now use psychosomatic pressures, estrogenic substances and consumptive addictions to retard individuation and bind our social bodies together. As you read through the following, please recall how your schools prepared you "for the real world" as well as your own personal experiences with Big Bodies and their bonsai members.</FONT></BLOCKQUOTE>
<UL>
<LI>      <DL><STRONG>The Ki Papers</STRONG> <DD>A modest primer on what's going on in the corporate dominated body politic and the pants of the people.</DL>
<UL>

<LI><A href="${BASE_URL}kipower/kiarts.html" target="_blank"><STRONG>Ki and the Arts of Sex, Healing &amp; Corporate Body-Building</STRONG></A>
<LI><A href="${BASE_URL}kipower/kisoma.html" target="_blank"><STRONG>E Pluribus Yamato: The Culture of Corporate Beings</STRONG></A>
<LI><A href="${BASE_URL}kipower/mindbind.html" target="_blank"><STRONG>The Japanese Arts of Mind-Binding</STRONG></A>
</UL>
<LI><A href="${BASE_URL}cityhall/rectmeme.html" target="_blank"><STRONG>History in Your Pants</STRONG></A>



<LI><A href="${BASE_URL}bigmed2001/bigread1.html#anthcult"><STRONG>Short Anthroculture Bibliography</STRONG></A>

<P>
</UL>
<STRONG><U>Better Ball-Busting through Chemistry</U></STRONG><BR>
<BLOCKQUOTE><FONT  COLOR=#800000>We once believed industrial emasculation was simply done with authoritarian instruction, systemic stress and  estrogenic foods. Now it turns out Big Bodies have also been flooding the food chain with male hormone disruptors and thus prepping us all for a lifelong pre-sexual childhood. Won't Disney be thrilled...</FONT></BLOCKQUOTE>
<UL>
<LI>      <DT><A href="${BASE_URL}anthcult/euknacks.html" target="_blank"> <STRONG>Common Pollutants Undermine Masculinity</STRONG></A> - By J. Raloff, from
Science News Online
<LI>     <DT><A HREF="http://madcow.newscientist.com/nsplus/insight/fertility/missing.html" target="_blank"><STRONG>Some of our sperm are missing</STRONG></A> New Scientist report
<LI>      <DT><A href="${BASE_URL}bigbody/ehradio.html" target="_blank"> <STRONG>Environmental Hormones</STRONG></A> (Big Medicine radio script)
<LI>    <DT><A HREF="http://www.som.tulane.edu/ecme/eehome/" target="_blank"><STRONG>Environmental Estrogens</STRONG></A> - Tulane University's Dynamite Site!
<LI>   <DT><A HREF="http://www.tmc.tulane.edu/ECME/eehome/newsviews/whatsnew/" target="_blank"><STRONG>Endocrine Disruptor News</STRONG></A> - See especially confirmation report on low-dose effect, industry convulsion on its way.<br>
<BLOCKQUOTE><FONT  COLOR=#800000>"The National Toxicology Program (NTP) released a draft report May 14
                      reviewing scientific evidence for low-dose effects of natural and synthetic
                      endocrine disruptors. The 36-member expert panel reports that some
                      studies provide evidence for effects at very low doses. The panel reviewed scientific data on
                      environmental estrogens, estradiol, and androgens. According to the
                      report's executive summary, substances with positive, estrogenic
                      low-dose effects include bisphenol A, diethylstilbestrol (DES), estradiol,
                      genistein, methoxychlor, nonylphenol, and ocylphenol."</FONT></BLOCKQUOTE>



<P>

<LI>For more references, see: <BR><A href="${BASE_URL}bigmed2001/bigstres.html"><STRONG>UNDERSTANDING  BIG BODY ANTHROCULTURE</STRONG></A><BR>  Artful Emasculation for Terminal Incorporation

</UL>

<STRONG><U>Anthroculture for Eusociality, Neoteny, <BR>and the Corporate Valhalla</U></STRONG><BR>

<BLOCKQUOTE><FONT  COLOR=#800000>The ultimate target of all anthrocultural enterprise is a eusocial  or perfectly submissive collective body. (Eusocial means "REALLY social", to the point that worker members become literally "self-sacrificing" &amp;  "single-minded", reflexively obedient and effectively neuter.  Among humans the neutering  is less genetic than memetic -- the males can no longer freely produce or act upon their own seminal ideas. Their personal conceptions are gradually replaced with the orthodox memes of their corporate body which they learn to accept as their own.) Eusocial underlings thus enter a prolonged state of neoteny or arrested psychosomatic development. The following readings may make this all a bit clearer.</FONT></BLOCKQUOTE>

<UL>

<LI>        <DL><A HREF="http://www.life.uiuc.edu/bio104/" target="_blank"> <STRONG>Eusocial Bodies</STRONG>
</A> - Sociobiology Perspectives (University of Illinois)<dd><BR>
                     
<U><STRONG>Excerpts</STRONG></U><BR>
"The most extreme form of individual self-sacrifice is found among a very small number of species
referred to as <U>eusocial</U>. In eusocial species, reproduction is limited to a very few members of
the society. The examples you are probably already familiar with are the social insects: bees,
wasps, ants, and termites...The colonies of social insects are in some
respects like organisms... These insects live together in enduring colonies (often tens of thousands of
individuals) and have a strict hierarchical social organization...<P>

"There are three members of a honey bee society: the queen , the
male drones, and the workers. What about those tens of thousands of
workers? They are all sterile. Their lives are devoted to tending the hive, producing the
honeycomb, finding food and water, and defending the hive against
aggressors. <P>


"Ants, wasps, and bees are all so closely
related that we find them within a single order of insects -- Hymenoptera. But 
termites are in a totally different order -- Isoptera. Their closest relatives are the cockroaches. The eusociality of
these different types of insects -- bees and termites -- therefore represents a case of convergent
evolution.<P>

"An even more spectacular case of convergent evolution is seen in the case of the naked
mole-rats. These are the mammalian equivalent of termites -- a single queen mates with one or two kings, and everyone else serves as a sterile worker. These are the only known eusocial vertebrates." (The good doctor has obviously never visited Mitsubishi...)</DL><P>

<LI>        <DL><A HREF="http://www.discovery.com/stories/nature/animalfamilies/award1.html" target="_blank"><STRONG>Naked Mole-Rats</STRONG></A><dd><P>
              

<U><STRONG>Excerpts</STRONG></U><BR>
"The only "eusocial" mammals, these mondo bizzarro creatures from sub-Saharan
                 Africa live in communal nests in dark burrow systems where
                 they are ruled by a caste system similar to that of social insects.  Naked mole-rats grow up only to serve
                 the needs of their plump CEO queen -- the sole female breeder in the colony.
                 Once weaned, the young mole-rats join the working class. Unlike ants, worker
                 mole-rats are not sterile. So what stops them all from breeding? Biologists think the
                 matriarch uses hormones to suppress reproduction in the rest of the colony. During the queen mama's estrus cycle, all the male mole-rat                  underlings develop teats and run around looking like females." Similar hormones also seem to chronically block maturation and prepare the workers for life-long neutered service to the collective enterprise. This arrested state is similar to classical neoteny.</DL><P>

<LI>        <DL><A HREF="http://www.grandin.com/references/genetics.html" target="_blank"><STRONG>Neoteny, 
Genetics and Domestic Animal Behavior</STRONG></A><dd>
"Neoteny is the retention of juvenile features in an adult animal.  Neoteny is manifested both behaviorally and physically. In the forward to "The Wild Canids," Konrad Lorenz adds a few of his observations on neoteny and the problems of domestication: 

<BLOCKQUOTE>     'The problems of domestication have been an obsession with me for many years. On the one hand, I
     am convinced that man owes the life-long persistence of his explorative
     playfulness to a partial neoteny which is indubitably a consequence of domestication In a curiously
     analogous manner does the domestic dog owe its permanent attachment to its master to a behavioral
     neoteny that <U>prevents it from ever wanting to be a pack leader</U> On the other hand, domestication is
     apt to cause an alarming disintegration of valuable behavioral traits and an equally alarming
     exaggeration of less desirable ones.'</BLOCKQUOTE> 

"Infantile characteristics in domestic animals are discussed by Price and Coppinger et al. (1987). The physical changes are also related to changes in behavior. <U>Retaining juvenile traits makes animals more tractable and easy to handle."</U> (Emphasis added.)</DL>

</UL>
<CENTER><IMG SRC="${BASE_URL}bigmed2001/graph/advline2.gif" WIDTH=100% HEIGHT=5></CENTER>
`;

  return (
    <div
      className="min-h-screen w-full legacy-page-wrapper"
      style={{ fontFamily: "Times New Roman, Georgia, serif", backgroundColor: 'beige', backgroundImage: `url(${BASE_URL}barks/paper2.gif)`, backgroundRepeat: 'repeat', color: '#000000' }}
    >
      <style>{`
  a { color: #1a40b8; text-decoration: underline; font-weight: bold; }
  a:hover { color: #cc0000; }
  h1, h2, h3, h4, h5, h6 { font-weight: bold; margin-bottom: 0.75em; }
  strong, b { font-weight: 900; }
  ul, ol { padding-left: 2em; margin-bottom: 1em; }
  li { margin-bottom: 0.5em; }
  img { max-width: 100%; height: auto; display: inline-block; }
  blockquote {
    padding-left: 1.5em;
    margin: 1em 2em;
  }
  hr {
    border: 0;
    border-top: 2px solid #333;
    margin: 1.5em auto !important;
  }
  /* Center tag should center its children */
  center {
    display: block;
    text-align: center;
  }
  center table, table[align="center"], table[align="CENTER"], [align="center" i] table, [align="middle" i] table {
    margin-left: auto !important;
    margin-right: auto !important;
  }
  center hr, hr[align="center"], hr[align="CENTER"], [align="center" i] hr, [align="middle" i] hr {
    margin-left: auto !important;
    margin-right: auto !important;
  }
  hr[align="left"], hr[align="LEFT"] {
    margin-left: 0 !important;
    margin-right: auto !important;
  }
  hr[align="right"], hr[align="RIGHT"] {
    margin-left: auto !important;
    margin-right: 0 !important;
  }
  
  /* Alignment attribute mappings */
  [align="left"], [align="LEFT"] {
    text-align: left !important;
  }
  [align="right"], [align="RIGHT"] {
    text-align: right !important;
  }
  [align="center"], [align="CENTER"], [align="middle"], [align="MIDDLE"] {
    text-align: center !important;
  }
  
  td, th {
    text-align: left;
  }
  
  /* Responsive styles for screens smaller than 768px */
  @media (max-width: 767px) {
    blockquote {
      margin-left: 0.5em;
      margin-right: 0.5em;
      padding-left: 0.5em;
    }
    hr {
      width: 100% !important;
      margin: 1em auto !important;
    }
    table {
      width: 100% !important;
      display: block !important;
      overflow-x: auto !important;
    }
  }

  .legacy-page-wrapper, .legacy-page-wrapper :where(p, li, td, th, dd, dt, blockquote, div, span, font) { color: inherit; }
  a { color: #007339; }
  a:visited { color: #1866C5; }
`}</style>
      <div className="legacy-page-content">
        <div dangerouslySetInnerHTML={{ __html: html }} className="w-full" />
      </div>
    </div>
  );
};

export default Bigmed2001Bigonnet;
